BASE_URL = 'https://reqres.in'
RESOURCE_USERS = 'api/users/'
RESOURCE_LOGIN = 'api/login/'
RESOURCE_NOT_FOUND = 'api/unknown/23/'
RESOURCE_REGISTER = 'api/register/'
REQUEST_BODY_POST = '{"first_name": "morpheus","email": "mushroom@yandex.ru"}'
REQUEST_BODY_POST2 = '{"first_name": "Testers","email": "mus@hr.oom"}'
REQUEST_BODY_UPDATE = '{"first_name": "Testers","second_name": "second"}'
REQUEST_BODY_UPDATE2 = '{"first_name": "Testers","job": "IBS"}'
REQUEST_BODY_POST_NEGATIVE = '{"first_name": "morpheus", "email":, "ertet": "dgdfg"}'
REQUEST_BODY_POST_NEGATIVE2 = '{"first_name":, "email": "rt@yry", "ertet": "dgdfg"}'
DIRECTORY_LOGS = 'logs/'
DIRECTORY_TEST_REPORTS = 'test_reports/'


