BASE_URL = 'https://reqres.in/'
RESOURCE_USERS = 'api/users/'
REQUEST_BODY_POST = '{"first_name": "morpheus","email": "mushroom"}'
REQUEST_BODY_POST2 = '{"first_name": "Testers","email": "mus@hr.oom"}'
REQUEST_BODY_UPDATE = '{"first_name": "Testers","second_name": "second"}'
REQUEST_BODY_UPDATE2 = '{"first_name": "Testers","job": "IBS"}'
RESOURCE_REGISTER = 'api/register/'
